version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

homebrew_casks:
  - repository:
      owner: hayasedb
      name: homebrew-hayase-cli
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/hayasedb/hayase-cli"
    description: "A modern CLI tool for anime streaming"

scoops:
  - repository:
      owner: hayasedb
      name: scoop-hayase-cli
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/hayasedb/hayase-cli" 
    description: "A modern CLI tool for anime streaming"

aurs:
  - homepage: "https://github.com/hayasedb/hayase-cli"
    description: "A modern CLI tool for anime streaming"
    maintainers:
      - "hayasedb <noreply@github.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/hayase-cli.git"