name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@latest
        with:
          go-version: latest
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@latest
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}